// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddSimulatedPlayersReducer from "../add_simulated_players_reducer";
import CreateSessionReducer from "../create_session_reducer";
import CreateShareCardReducer from "../create_share_card_reducer";
import FinishMatchReducer from "../finish_match_reducer";
import HardResetDemoReducer from "../hard_reset_demo_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import IncrementShareViewReducer from "../increment_share_view_reducer";
import JoinSessionReducer from "../join_session_reducer";
import LiveTickReducer from "../live_tick_reducer";
import RecordAgentEventReducer from "../record_agent_event_reducer";
import RequestQuestionsReducer from "../request_questions_reducer";
import ResetDemoReducer from "../reset_demo_reducer";
import ResolveRoundReducer from "../resolve_round_reducer";
import SimulateAnswerBurstReducer from "../simulate_answer_burst_reducer";
import StartMatchReducer from "../start_match_reducer";
import StartRoundReducer from "../start_round_reducer";
import SubmitAnswerReducer from "../submit_answer_reducer";
import SubmitParsedIntentReducer from "../submit_parsed_intent_reducer";
import SubmitPlayerIntentReducer from "../submit_player_intent_reducer";
import SubmitQuestionBatchReducer from "../submit_question_batch_reducer";
import SubmitQuestionPackReducer from "../submit_question_pack_reducer";
import SubmitTopicFactsReducer from "../submit_topic_facts_reducer";
import SubmitTopicVoteReducer from "../submit_topic_vote_reducer";

export type AddSimulatedPlayersParams = __Infer<typeof AddSimulatedPlayersReducer>;
export type CreateSessionParams = __Infer<typeof CreateSessionReducer>;
export type CreateShareCardParams = __Infer<typeof CreateShareCardReducer>;
export type FinishMatchParams = __Infer<typeof FinishMatchReducer>;
export type HardResetDemoParams = __Infer<typeof HardResetDemoReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type IncrementShareViewParams = __Infer<typeof IncrementShareViewReducer>;
export type JoinSessionParams = __Infer<typeof JoinSessionReducer>;
export type LiveTickParams = __Infer<typeof LiveTickReducer>;
export type RecordAgentEventParams = __Infer<typeof RecordAgentEventReducer>;
export type RequestQuestionsParams = __Infer<typeof RequestQuestionsReducer>;
export type ResetDemoParams = __Infer<typeof ResetDemoReducer>;
export type ResolveRoundParams = __Infer<typeof ResolveRoundReducer>;
export type SimulateAnswerBurstParams = __Infer<typeof SimulateAnswerBurstReducer>;
export type StartMatchParams = __Infer<typeof StartMatchReducer>;
export type StartRoundParams = __Infer<typeof StartRoundReducer>;
export type SubmitAnswerParams = __Infer<typeof SubmitAnswerReducer>;
export type SubmitParsedIntentParams = __Infer<typeof SubmitParsedIntentReducer>;
export type SubmitPlayerIntentParams = __Infer<typeof SubmitPlayerIntentReducer>;
export type SubmitQuestionBatchParams = __Infer<typeof SubmitQuestionBatchReducer>;
export type SubmitQuestionPackParams = __Infer<typeof SubmitQuestionPackReducer>;
export type SubmitTopicFactsParams = __Infer<typeof SubmitTopicFactsReducer>;
export type SubmitTopicVoteParams = __Infer<typeof SubmitTopicVoteReducer>;

