// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ticketId: __t.string().primaryKey().name("ticket_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.string().name("participant_id"),
  status: __t.string(),
  queuePosition: __t.option(__t.u32()).name("queue_position"),
  issuedAtMs: __t.u64().name("issued_at_ms"),
});
