// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  sessionId: __t.string().name("session_id"),
  agentName: __t.string().name("agent_name"),
  eventType: __t.string().name("event_type"),
  content: __t.string(),
  confidence: __t.f32(),
  status: __t.string(),
  createdAtMs: __t.u64().name("created_at_ms"),
});
