// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  requestId: __t.string().primaryKey().name("request_id"),
  sessionId: __t.string().name("session_id"),
  requestType: __t.string().name("request_type"),
  topic: __t.string(),
  questionCount: __t.u32().name("question_count"),
  status: __t.string(),
  createdAtMs: __t.u64().name("created_at_ms"),
  updatedAtMs: __t.u64().name("updated_at_ms"),
  errorMessage: __t.option(__t.string()).name("error_message"),
});
