// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  answerId: __t.string().primaryKey().name("answer_id"),
  sessionId: __t.string().name("session_id"),
  roundId: __t.string().name("round_id"),
  questionId: __t.string().name("question_id"),
  participantId: __t.string().name("participant_id"),
  selectedOption: __t.string().name("selected_option"),
  isCorrect: __t.bool().name("is_correct"),
  responseMs: __t.u32().name("response_ms"),
  responseMsServer: __t.u32().name("response_ms_server"),
  clientSentAtMs: __t.option(__t.u64()).name("client_sent_at_ms"),
  clientEventId: __t.string().name("client_event_id"),
  correctnessPoints: __t.u32().name("correctness_points"),
  speedBonus: __t.u32().name("speed_bonus"),
  streakBonus: __t.u32().name("streak_bonus"),
  scoreDelta: __t.u32().name("score_delta"),
  serverReceivedAtMs: __t.u64().name("server_received_at_ms"),
  createdAtMs: __t.u64().name("created_at_ms"),
});
