// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  errorId: __t.string().primaryKey().name("error_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.string().name("participant_id"),
  screen: __t.string(),
  errorCode: __t.string().name("error_code"),
  message: __t.string(),
  stackHash: __t.option(__t.string()).name("stack_hash"),
  metadataJson: __t.string().name("metadata_json"),
  userAgent: __t.string().name("user_agent"),
  createdAtMs: __t.u64().name("created_at_ms"),
});
