// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  joinedCount: __t.u32().name("joined_count"),
  realJoinedCount: __t.u32().name("real_joined_count"),
  simulatedJoinedCount: __t.u32().name("simulated_joined_count"),
  answersCount: __t.u32().name("answers_count"),
  answersPerSec: __t.u32().name("answers_per_sec"),
  reducerCalls: __t.u32().name("reducer_calls"),
  duplicateAnswersRejected: __t.u32().name("duplicate_answers_rejected"),
  p95LatencyMs: __t.u32().name("p_95_latency_ms"),
  p95AnswerCommitMs: __t.u32().name("p_95_answer_commit_ms"),
  p95SubscriptionRenderMs: __t.u32().name("p_95_subscription_render_ms"),
  activeClients: __t.u32().name("active_clients"),
  admittedRacers: __t.u32().name("admitted_racers"),
  waitlistedUsers: __t.u32().name("waitlisted_users"),
  capacityStatus: __t.string().name("capacity_status"),
  updatedAtMs: __t.u64().name("updated_at_ms"),
});
