// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  traceId: __t.string().primaryKey().name("trace_id"),
  sessionId: __t.string().name("session_id"),
  reducer: __t.string(),
  identity: __t.string(),
  ok: __t.bool(),
  durationMs: __t.u32().name("duration_ms"),
  stateVersion: __t.u32().name("state_version"),
  errorMessage: __t.option(__t.string()).name("error_message"),
  createdAtMs: __t.u64().name("created_at_ms"),
});
