// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  participantId: __t.string().primaryKey().name("participant_id"),
  sessionId: __t.string().name("session_id"),
  identity: __t.string(),
  displayName: __t.string().name("display_name"),
  avatar: __t.string(),
  admissionStatus: __t.string().name("admission_status"),
  championStatus: __t.string().name("champion_status"),
  joinedAtMs: __t.u64().name("joined_at_ms"),
  lastSeenMs: __t.u64().name("last_seen_ms"),
  isSimulated: __t.bool().name("is_simulated"),
  clientLatencyMs: __t.option(__t.u32()).name("client_latency_ms"),
});
