// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  intentId: __t.string().primaryKey().name("intent_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.string().name("participant_id"),
  rawText: __t.string().name("raw_text"),
  transcriptSource: __t.string().name("transcript_source"),
  cleanedText: __t.string().name("cleaned_text"),
  canonicalTopicsJson: __t.string().name("canonical_topics_json"),
  topicKey: __t.string().name("topic_key"),
  arenaName: __t.string().name("arena_name"),
  difficultyHint: __t.string().name("difficulty_hint"),
  confidence: __t.f32(),
  status: __t.string(),
  createdAtMs: __t.u64().name("created_at_ms"),
  updatedAtMs: __t.u64().name("updated_at_ms"),
});
