// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  questionId: __t.string().primaryKey().name("question_id"),
  packId: __t.option(__t.string()).name("pack_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.option(__t.string()).name("participant_id"),
  topicKey: __t.string().name("topic_key"),
  orderIndex: __t.u32().name("order_index"),
  questionText: __t.string().name("question_text"),
  optionA: __t.string().name("option_a"),
  optionB: __t.string().name("option_b"),
  optionC: __t.string().name("option_c"),
  optionD: __t.string().name("option_d"),
  displayTopic: __t.string().name("display_topic"),
  topic: __t.string(),
  generatedBy: __t.string().name("generated_by"),
  fairnessStatus: __t.string().name("fairness_status"),
  createdAtMs: __t.u64().name("created_at_ms"),
  sourceTitle: __t.string().name("source_title"),
  sourceUrl: __t.string().name("source_url"),
});
