// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  sessionId: __t.option(__t.string()),
  participantId: __t.option(__t.string()),
  screen: __t.string(),
  errorCode: __t.string(),
  message: __t.string(),
  stackHash: __t.option(__t.string()),
  metadataJson: __t.string(),
  userAgent: __t.string(),
};
