// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roundId: __t.string().primaryKey().name("round_id"),
  sessionId: __t.string().name("session_id"),
  questionId: __t.string().name("question_id"),
  orderIndex: __t.u32().name("order_index"),
  status: __t.string(),
  startsAtMs: __t.u64().name("starts_at_ms"),
  endsAtMs: __t.u64().name("ends_at_ms"),
  resolvedAtMs: __t.option(__t.u64()).name("resolved_at_ms"),
});
