// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  maxRacersSoft: __t.u32().name("max_racers_soft"),
  maxRacersHard: __t.u32().name("max_racers_hard"),
  admittedCount: __t.u32().name("admitted_count"),
  waitlistedCount: __t.u32().name("waitlisted_count"),
  spectatorCount: __t.u32().name("spectator_count"),
  status: __t.string(),
  reason: __t.option(__t.string()),
  updatedAtMs: __t.u64().name("updated_at_ms"),
});
