// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  factId: __t.string().primaryKey().name("fact_id"),
  sessionId: __t.string().name("session_id"),
  topicKey: __t.string().name("topic_key"),
  displayName: __t.string().name("display_name"),
  sourceTitle: __t.string().name("source_title"),
  sourceUrl: __t.string().name("source_url"),
  sourceType: __t.string().name("source_type"),
  factText: __t.string().name("fact_text"),
  confidence: __t.f32(),
  createdAtMs: __t.u64().name("created_at_ms"),
});
