// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.option(__t.string()).name("participant_id"),
  eventType: __t.string().name("event_type"),
  roundIndex: __t.option(__t.u32()).name("round_index"),
  scoreAfter: __t.option(__t.u32()).name("score_after"),
  rankAfter: __t.option(__t.u32()).name("rank_after"),
  payloadJson: __t.string().name("payload_json"),
  createdAtMs: __t.u64().name("created_at_ms"),
});
