// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  packId: __t.string().primaryKey().name("pack_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.option(__t.string()).name("participant_id"),
  topicKey: __t.string().name("topic_key"),
  displayTopic: __t.string().name("display_topic"),
  sourceType: __t.string().name("source_type"),
  qualityScore: __t.u32().name("quality_score"),
  status: __t.string(),
  createdAtMs: __t.u64().name("created_at_ms"),
});
