// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  scoreId: __t.string().primaryKey().name("score_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.string().name("participant_id"),
  totalScore: __t.u32().name("total_score"),
  correctCount: __t.u32().name("correct_count"),
  wrongCount: __t.u32().name("wrong_count"),
  answeredCount: __t.u32().name("answered_count"),
  totalResponseMs: __t.u32().name("total_response_ms"),
  fastestResponseMs: __t.option(__t.u32()).name("fastest_response_ms"),
  averageResponseMs: __t.option(__t.u32()).name("average_response_ms"),
  normalizedScore: __t.f32().name("normalized_score"),
  streakCount: __t.u32().name("streak_count"),
  lastAnswerCorrect: __t.option(__t.bool()).name("last_answer_correct"),
  championStatus: __t.string().name("champion_status"),
  currentRank: __t.u32().name("current_rank"),
  previousRank: __t.u32().name("previous_rank"),
  lastAnswerAtMs: __t.option(__t.u64()).name("last_answer_at_ms"),
  updatedAtMs: __t.u64().name("updated_at_ms"),
});
