// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.string().primaryKey().name("session_id"),
  code: __t.string(),
  status: __t.string(),
  selectedTopic: __t.option(__t.string()).name("selected_topic"),
  questionCount: __t.u32().name("question_count"),
  currentRound: __t.u32().name("current_round"),
  matchStartedAtMs: __t.option(__t.u64()).name("match_started_at_ms"),
  matchFinishedAtMs: __t.option(__t.u64()).name("match_finished_at_ms"),
  maxRacers: __t.u32().name("max_racers"),
  admittedCount: __t.u32().name("admitted_count"),
  capacityStatus: __t.string().name("capacity_status"),
  capacityReason: __t.option(__t.string()).name("capacity_reason"),
  createdAtMs: __t.u64().name("created_at_ms"),
  updatedAtMs: __t.u64().name("updated_at_ms"),
});
