// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  shareId: __t.string().primaryKey().name("share_id"),
  slug: __t.string(),
  sessionId: __t.string().name("session_id"),
  participantId: __t.string().name("participant_id"),
  displayName: __t.string().name("display_name"),
  avatar: __t.string(),
  avatarType: __t.string().name("avatar_type"),
  avatarEmoji: __t.option(__t.string()).name("avatar_emoji"),
  avatarColor: __t.option(__t.string()).name("avatar_color"),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  displayTopic: __t.string().name("display_topic"),
  finalRank: __t.u32().name("final_rank"),
  totalParticipants: __t.u32().name("total_participants"),
  championStatus: __t.string().name("champion_status"),
  totalScore: __t.u32().name("total_score"),
  correctCount: __t.u32().name("correct_count"),
  questionCount: __t.u32().name("question_count"),
  totalResponseMsOfficial: __t.u32().name("total_response_ms_official"),
  totalResponseMsObserved: __t.option(__t.u32()).name("total_response_ms_observed"),
  fastestResponseMs: __t.option(__t.u32()).name("fastest_response_ms"),
  fastestResponseMsOfficial: __t.option(__t.u32()).name("fastest_response_ms_official"),
  fastestResponseMsObserved: __t.option(__t.u32()).name("fastest_response_ms_observed"),
  percentile: __t.u32(),
  shareText: __t.string().name("share_text"),
  createdAtMs: __t.u64().name("created_at_ms"),
  expiresAtMs: __t.option(__t.u64()).name("expires_at_ms"),
  viewCount: __t.u32().name("view_count"),
});
