// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  voteId: __t.string().primaryKey().name("vote_id"),
  sessionId: __t.string().name("session_id"),
  participantId: __t.string().name("participant_id"),
  topic: __t.string(),
  createdAtMs: __t.u64().name("created_at_ms"),
});
