// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdmissionTicket = __t.object("AdmissionTicket", {
  ticketId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.string(),
  status: __t.string(),
  queuePosition: __t.option(__t.u32()),
  issuedAtMs: __t.u64(),
});
export type AdmissionTicket = __Infer<typeof AdmissionTicket>;

export const AgentEvent = __t.object("AgentEvent", {
  eventId: __t.string(),
  sessionId: __t.string(),
  agentName: __t.string(),
  eventType: __t.string(),
  content: __t.string(),
  confidence: __t.f32(),
  status: __t.string(),
  createdAtMs: __t.u64(),
});
export type AgentEvent = __Infer<typeof AgentEvent>;

export const AgentRequest = __t.object("AgentRequest", {
  requestId: __t.string(),
  sessionId: __t.string(),
  requestType: __t.string(),
  topic: __t.string(),
  questionCount: __t.u32(),
  status: __t.string(),
  createdAtMs: __t.u64(),
  updatedAtMs: __t.u64(),
  errorMessage: __t.option(__t.string()),
});
export type AgentRequest = __Infer<typeof AgentRequest>;

export const Answer = __t.object("Answer", {
  answerId: __t.string(),
  sessionId: __t.string(),
  roundId: __t.string(),
  questionId: __t.string(),
  participantId: __t.string(),
  selectedOption: __t.string(),
  isCorrect: __t.bool(),
  responseMs: __t.u32(),
  responseMsServer: __t.u32(),
  officialResponseMs: __t.u32(),
  observedResponseMs: __t.option(__t.u32()),
  clientQuestionRenderedAtMs: __t.option(__t.u64()),
  clientClickedAtMs: __t.option(__t.u64()),
  clientSentAtMs: __t.option(__t.u64()),
  clientEventId: __t.string(),
  correctnessPoints: __t.u32(),
  speedBonus: __t.u32(),
  streakBonus: __t.u32(),
  scoreDelta: __t.u32(),
  serverReceivedAtMs: __t.u64(),
  serverCommittedAtMs: __t.u64(),
  participantLatencyMsSnapshot: __t.option(__t.u32()),
  timingSuspicious: __t.bool(),
  createdAtMs: __t.u64(),
});
export type Answer = __Infer<typeof Answer>;

export const AuditEvent = __t.object("AuditEvent", {
  auditId: __t.string(),
  sessionId: __t.string(),
  actorIdentity: __t.string(),
  eventType: __t.string(),
  message: __t.string(),
  createdAtMs: __t.u64(),
});
export type AuditEvent = __Infer<typeof AuditEvent>;

export const ClientError = __t.object("ClientError", {
  errorId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.string(),
  screen: __t.string(),
  errorCode: __t.string(),
  message: __t.string(),
  stackHash: __t.option(__t.string()),
  metadataJson: __t.string(),
  userAgent: __t.string(),
  createdAtMs: __t.u64(),
});
export type ClientError = __Infer<typeof ClientError>;

export const FinalResult = __t.object("FinalResult", {
  finalResultId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.string(),
  finalRank: __t.u32(),
  totalParticipants: __t.u32(),
  championStatus: __t.string(),
  totalScore: __t.u32(),
  correctCount: __t.u32(),
  questionCount: __t.u32(),
  answeredCount: __t.u32(),
  totalAnswerResponseMs: __t.u32(),
  totalCorrectResponseMs: __t.u32(),
  totalResponseMs: __t.u32(),
  totalOfficialResponseMs: __t.u32(),
  fastestResponseMs: __t.option(__t.u32()),
  fastestOfficialResponseMs: __t.option(__t.u32()),
  averageOfficialResponseMs: __t.option(__t.u32()),
  normalizedScore: __t.f32(),
  percentile: __t.u32(),
  createdAtMs: __t.u64(),
});
export type FinalResult = __Infer<typeof FinalResult>;

export const LiveStats = __t.object("LiveStats", {
  sessionId: __t.string(),
  joinedCount: __t.u32(),
  realJoinedCount: __t.u32(),
  simulatedJoinedCount: __t.u32(),
  answersCount: __t.u32(),
  answersPerSec: __t.u32(),
  reducerCalls: __t.u32(),
  duplicateAnswersRejected: __t.u32(),
  p95LatencyMs: __t.u32(),
  p95AnswerCommitMs: __t.u32(),
  p95SubscriptionRenderMs: __t.u32(),
  activeClients: __t.u32(),
  admittedRacers: __t.u32(),
  waitlistedUsers: __t.u32(),
  capacityStatus: __t.string(),
  updatedAtMs: __t.u64(),
});
export type LiveStats = __Infer<typeof LiveStats>;

export const MatchEvent = __t.object("MatchEvent", {
  eventId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.option(__t.string()),
  eventType: __t.string(),
  roundIndex: __t.option(__t.u32()),
  scoreAfter: __t.option(__t.u32()),
  rankAfter: __t.option(__t.u32()),
  payloadJson: __t.string(),
  createdAtMs: __t.u64(),
});
export type MatchEvent = __Infer<typeof MatchEvent>;

export const OperationTrace = __t.object("OperationTrace", {
  traceId: __t.string(),
  sessionId: __t.string(),
  reducer: __t.string(),
  identity: __t.string(),
  ok: __t.bool(),
  durationMs: __t.u32(),
  stateVersion: __t.u32(),
  errorMessage: __t.option(__t.string()),
  createdAtMs: __t.u64(),
});
export type OperationTrace = __Infer<typeof OperationTrace>;

export const Participant = __t.object("Participant", {
  participantId: __t.string(),
  sessionId: __t.string(),
  identity: __t.string(),
  displayName: __t.string(),
  avatar: __t.string(),
  admissionStatus: __t.string(),
  championStatus: __t.string(),
  joinedAtMs: __t.u64(),
  lastSeenMs: __t.u64(),
  isSimulated: __t.bool(),
  clientLatencyMs: __t.option(__t.u32()),
});
export type Participant = __Infer<typeof Participant>;

export const PlayerIntent = __t.object("PlayerIntent", {
  intentId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.string(),
  rawText: __t.string(),
  transcriptSource: __t.string(),
  cleanedText: __t.string(),
  canonicalTopicsJson: __t.string(),
  topicKey: __t.string(),
  arenaName: __t.string(),
  difficultyHint: __t.string(),
  confidence: __t.f32(),
  status: __t.string(),
  createdAtMs: __t.u64(),
  updatedAtMs: __t.u64(),
});
export type PlayerIntent = __Infer<typeof PlayerIntent>;

export const QuestionPack = __t.object("QuestionPack", {
  packId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.option(__t.string()),
  topicKey: __t.string(),
  displayTopic: __t.string(),
  sourceType: __t.string(),
  qualityScore: __t.u32(),
  status: __t.string(),
  createdAtMs: __t.u64(),
});
export type QuestionPack = __Infer<typeof QuestionPack>;

export const QuestionPublic = __t.object("QuestionPublic", {
  questionId: __t.string(),
  packId: __t.option(__t.string()),
  sessionId: __t.string(),
  participantId: __t.option(__t.string()),
  topicKey: __t.string(),
  orderIndex: __t.u32(),
  questionText: __t.string(),
  optionA: __t.string(),
  optionB: __t.string(),
  optionC: __t.string(),
  optionD: __t.string(),
  displayTopic: __t.string(),
  topic: __t.string(),
  generatedBy: __t.string(),
  fairnessStatus: __t.string(),
  createdAtMs: __t.u64(),
  sourceTitle: __t.string(),
  sourceUrl: __t.string(),
});
export type QuestionPublic = __Infer<typeof QuestionPublic>;

export const QuestionSecret = __t.object("QuestionSecret", {
  questionId: __t.string(),
  packId: __t.option(__t.string()),
  sessionId: __t.string(),
  participantId: __t.option(__t.string()),
  correctOption: __t.string(),
  explanation: __t.string(),
  factIdsJson: __t.string(),
  createdAtMs: __t.u64(),
});
export type QuestionSecret = __Infer<typeof QuestionSecret>;

export const Round = __t.object("Round", {
  roundId: __t.string(),
  sessionId: __t.string(),
  questionId: __t.string(),
  orderIndex: __t.u32(),
  status: __t.string(),
  startsAtMs: __t.u64(),
  endsAtMs: __t.u64(),
  resolvedAtMs: __t.option(__t.u64()),
});
export type Round = __Infer<typeof Round>;

export const Score = __t.object("Score", {
  scoreId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.string(),
  totalScore: __t.u32(),
  correctCount: __t.u32(),
  wrongCount: __t.u32(),
  answeredCount: __t.u32(),
  totalAnswerResponseMs: __t.u32(),
  totalCorrectResponseMs: __t.u32(),
  totalResponseMs: __t.u32(),
  totalOfficialResponseMs: __t.u32(),
  totalObservedResponseMs: __t.option(__t.u32()),
  fastestResponseMs: __t.option(__t.u32()),
  fastestOfficialResponseMs: __t.option(__t.u32()),
  fastestObservedResponseMs: __t.option(__t.u32()),
  averageResponseMs: __t.option(__t.u32()),
  averageOfficialResponseMs: __t.option(__t.u32()),
  normalizedScore: __t.f32(),
  streakCount: __t.u32(),
  lastAnswerCorrect: __t.option(__t.bool()),
  championStatus: __t.string(),
  currentRank: __t.u32(),
  previousRank: __t.u32(),
  lastAnswerAtMs: __t.option(__t.u64()),
  updatedAtMs: __t.u64(),
});
export type Score = __Infer<typeof Score>;

export const Session = __t.object("Session", {
  sessionId: __t.string(),
  code: __t.string(),
  status: __t.string(),
  selectedTopic: __t.option(__t.string()),
  questionCount: __t.u32(),
  currentRound: __t.u32(),
  matchStartedAtMs: __t.option(__t.u64()),
  matchFinishedAtMs: __t.option(__t.u64()),
  maxRacers: __t.u32(),
  admittedCount: __t.u32(),
  capacityStatus: __t.string(),
  capacityReason: __t.option(__t.string()),
  createdAtMs: __t.u64(),
  updatedAtMs: __t.u64(),
});
export type Session = __Infer<typeof Session>;

export const SessionCapacity = __t.object("SessionCapacity", {
  sessionId: __t.string(),
  maxRacersSoft: __t.u32(),
  maxRacersHard: __t.u32(),
  admittedCount: __t.u32(),
  waitlistedCount: __t.u32(),
  spectatorCount: __t.u32(),
  status: __t.string(),
  reason: __t.option(__t.string()),
  updatedAtMs: __t.u64(),
});
export type SessionCapacity = __Infer<typeof SessionCapacity>;

export const ShareCard = __t.object("ShareCard", {
  shareId: __t.string(),
  slug: __t.string(),
  sessionId: __t.string(),
  participantId: __t.string(),
  displayName: __t.string(),
  avatar: __t.string(),
  avatarType: __t.string(),
  avatarEmoji: __t.option(__t.string()),
  avatarColor: __t.option(__t.string()),
  avatarUrl: __t.option(__t.string()),
  displayTopic: __t.string(),
  finalRank: __t.u32(),
  totalParticipants: __t.u32(),
  championStatus: __t.string(),
  totalScore: __t.u32(),
  correctCount: __t.u32(),
  questionCount: __t.u32(),
  answeredCount: __t.u32(),
  totalAnswerResponseMs: __t.u32(),
  totalCorrectResponseMs: __t.u32(),
  totalResponseMsOfficial: __t.u32(),
  totalResponseMsObserved: __t.option(__t.u32()),
  fastestResponseMs: __t.option(__t.u32()),
  fastestResponseMsOfficial: __t.option(__t.u32()),
  fastestResponseMsObserved: __t.option(__t.u32()),
  percentile: __t.u32(),
  shareText: __t.string(),
  createdAtMs: __t.u64(),
  expiresAtMs: __t.option(__t.u64()),
  viewCount: __t.u32(),
});
export type ShareCard = __Infer<typeof ShareCard>;

export const TopicFact = __t.object("TopicFact", {
  factId: __t.string(),
  sessionId: __t.string(),
  topicKey: __t.string(),
  displayName: __t.string(),
  sourceTitle: __t.string(),
  sourceUrl: __t.string(),
  sourceType: __t.string(),
  factText: __t.string(),
  confidence: __t.f32(),
  createdAtMs: __t.u64(),
});
export type TopicFact = __Infer<typeof TopicFact>;

export const TopicVote = __t.object("TopicVote", {
  voteId: __t.string(),
  sessionId: __t.string(),
  participantId: __t.string(),
  topic: __t.string(),
  createdAtMs: __t.u64(),
});
export type TopicVote = __Infer<typeof TopicVote>;

